version: "3.7"

services:
  db:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
      - "29015:29015"
      - "28015:28015"
    volumes:
      - rethink-data:/data
    networks:
      - parabol-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - parabol-network
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
      target: prod
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    labels:
      - traefik.backend=retro
      - traefik.frontend.rule=Host:retro.agilitytools.online
      - traefik.docker.network=web
      - traefik.port=3000
      - traefik.docker.network=traefik_default
    
    networks:
      - parabol-network
      - web
      - default
networks:
  parabol-network:
  web:
    external: true
  internal:
    external: false
volumes:
  redis-data: {}
  rethink-data: {}
